version: '3'

services:
  hsebot:
    build: .
    command: python main.py
    volumes:
      - .:/app
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: botbase
      POSTGRES_USER: annaerm
      POSTGRES_PASSWORD: qwer1234
