version: '3'

services:
  hsebot:
    build: .
    command: python main.py
    volumes:
      - .:/app
      - /home/annermolina/Documents/schedule-401419-59d99eeeb42a.json:/app/schedule-401419-59d99eeeb42a.json
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: botbase
      POSTGRES_USER: annaerm
      POSTGRES_PASSWORD: qwer1234
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "anya.ermolina@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "qwer1234"
    ports:
      - "5050:80"
    depends_on:
      - database

volumes:
  pgdata:
